default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  # If you using docker the host should be "db", if not "localhost"
  host: db
  port: 5432

development:
 <<: *default
 database: rails_api_base_development

test:
 <<: *default
 database: rails_api_base_test

production:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>
